# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c985367cf11a3817395d6e6b5df0a0a4f86528a0831445558907336da3f2f2581e0b486d0be68fd648fea18fcd41ef68e1aab382f67ab700fcbbab1a9799e90

test:
  secret_key_base: d40f2bd179b8ce2963a817c25c90bb99afa0322a531fcff46b2bcc4a633ec3652415b0942460589ff4482e5ea0c227f796201ab4593bea9a12adc52b97289ed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
